name = "EmbossPDE"
uuid = "af4c70bd-cfb7-4661-bec4-485750df9947"
authors = ["Tim Moroney <t.moroney@qut.edu.au> and contributors"]
version = "0.1.0-DEV"

[deps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
DoubleFloats = "1"
GenericLinearAlgebra = "0.3"
IntervalSets = "0.7"
LinearAlgebra = "1"
Polynomials = "4"
Requires = "1"
Test = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
